export const Loading = [
  "Entering the darkness, hold tight...",
  "Venturing into the unknown, stay alert...",
  "Descend into the abyss, the next chapter awaits...",
  "Brace yourself for the next level of terror...",
  "Be patient, the shadows are shifting...",
  "The veil is thinning, prepare for the next phase...",
  "The spirits are restless, the next scene is forming...",
  "Beware the lurking horrors, the next challenge approaches...",
  "Listen closely, the whispers of the next chapter can be heard...",
  "The mists are thickening, the next part of your journey is revealed...",
  "Unraveling the secrets, just a moment...",
  "The next part of your journey is being prepared...",
  "The shadows are stirring, please wait...",
  "The darkness is watching, loading...",
  "Whispers from the unknown, hold tight...",
  "The unknown lurks, be patient...",
  "The shadows are closing in, just a moment...",
  "The air is thick with anticipation, please wait...",
  "The darkness is hungry, loading...",
  "The unknown beckons, hold on...",
  "The secrets of the unknown await, please wait...",
  "The darkness conceals many secrets, loading...",
  "The veil of mystery is thick, be patient...",
  "Unraveling the enigma, hold on...",
  "The shadows hold many secrets, loading...",
  "The unknown is calling, just a moment...",
  "The mysteries of the unseen, loading...",
  "The unknown is unfathomable, please wait...",
  "The unknown is vast and impenetrable, loading...",
  "The secrets of the void await, hold tight...",
  "The forces of light and dark are in balance, please wait...",
  "Calling forth the ghosts in the machine, loading...",
];
